image: python:3.13-trixie

variables:
  MINARCA_DEV_REMOTE_URL: https://minarca-dev.ikus-soft.com
  MINARCA_DEV_USERNAME: admin
  MINARCA_DEV_PASSWORD: admin123

stages:
  - test
  - package
  - doc
  - test-package
  - sonar
  - publish
  - upload
  - deploy
  - e2e-test

.apt-minarca-source: &apt-minarca-source
  - wget -O /etc/apt/keyrings/minarca-keyring.asc https://www.ikus-soft.com/archive/minarca/public.key
  - echo "deb [arch=amd64 signed-by=/etc/apt/keyrings/minarca-keyring.asc] https://nexus.ikus-soft.com/repository/apt-dev-$DIST/ $DIST-dev main" > /etc/apt/sources.list.d/minarca.list
  - echo "deb [arch=amd64 signed-by=/etc/apt/keyrings/minarca-keyring.asc] https://nexus.ikus-soft.com/repository/apt-release-$DIST/ $DIST main" >> /etc/apt/sources.list.d/minarca.list
  - apt update

#
# Test Stage
#
.tox: &tox
  stage: test
  variables:
    TOXENV: $CI_JOB_NAME
  before_script:
    - apt-get -yq update
    - apt-get install -yq rdiff-backup
  script:
    - pip install tox
    - export TOXENV=${TOXENV:-$CI_JOB_NAME}
    - echo TOXENV=$TOXENV
    - ulimit -n 4096
    - tox
  artifacts:
    paths:
      - coverage-*.xml
      - xunit-*.xml
    expire_in: 1 day

lint:
  <<: *tox

py3:
  <<: *tox
  parallel: 3
  variables:
    TOXENV: "py3"
    PYTEST_SPLITS: $CI_NODE_TOTAL
    PYTEST_GROUP: $CI_NODE_INDEX

minarca:
  <<: *tox

selenium:
  <<: *tox
  parallel: 3
  variables:
    TOXENV: "selenium"
    PYTEST_SPLITS: $CI_NODE_TOTAL
    PYTEST_GROUP: $CI_NODE_INDEX
  before_script:
    - apt update
    - apt -y --no-install-recommends install xvfb xauth chromium-driver rdiff-backup
  artifacts:
    paths:
      - coverage.xml
      - xunit.xml

wrap-and-sort:
  stage: test
  image: buildpack-deps:stable
  script:
  - apt update
  - apt -y --no-install-recommends install devscripts python3-debian
  - CHANGES=$(wrap-and-sort -astN)
  - if [[ ! -z "$CHANGES" ]]; then echo "$CHANGES"; exit 1; fi

postgresql-12:
  <<: *tox
  image: python:3.13-trixie
  services:
    - postgres:16
  parallel: 3
  variables:
    TOXENV: trixie
    PYTEST_SPLITS: $CI_NODE_TOTAL
    PYTEST_GROUP: $CI_NODE_INDEX
    RDIFFWEB_TEST_DATABASE_URI: "postgresql://admin@postgres/test"
    POSTGRES_DB: test
    POSTGRES_USER: admin
    POSTGRES_PASSWORD: ""
    POSTGRES_HOST_AUTH_METHOD: trust

doc:
  <<: *tox
  stage: doc
  needs: []
  dependencies: []
  artifacts:
    paths:
      - .tox/doc/tmp/html
    expire_in: 1 day

package:py3:
  stage: package
  needs: []
  script:
    - pip3 install wheel build
    - python -m build
  dependencies: []
  artifacts:
    paths:
      - dist/*.whl
      - dist/*.tar.gz
    expire_in: 1 day

package:docker:
  stage: package
  needs: []
  dependencies: []
  image: docker:20
  services:
    - name: docker:20-dind
  parallel:
    matrix:
      - PKGAPP: rdiffweb
      - PKGAPP: minarca-server
        CWD: minarca-server/docker
  script:
    - cd "$CWD"
    - docker pull ikus060/$PKGAPP:latest || true
    - docker pull ikus060/$PKGAPP:$CI_COMMIT_REF_SLUG || true
    - docker build --cache-from ikus060/$PKGAPP:latest --cache-from ikus060/$PKGAPP:$CI_COMMIT_REF_SLUG -t $PKGAPP .
    - mkdir dist
    - mkdir -p $CI_PROJECT_DIR/dist
    - docker save $PKGAPP --output $CI_PROJECT_DIR/dist/$PKGAPP-docker.tar
  artifacts:
    paths:
      - dist/*-docker.tar
    expire_in: 1 day

package:rdiffweb:deb:
  stage: package
  needs: []
  image: buildpack-deps:$DIST
  parallel:
    matrix:
      - DIST: [trixie, forky]
      # Disable selenium test in ubuntu - because snap chronium is not working in docker
      - DIST: [questing, resolute]
        RDIFFWEB_SELENIUM_TEST: 0
  before_script:
    - *apt-minarca-source
  script:
    # Clean-up
    - rm -f ../*.deb
    - rm -Rf ./dist/$DIST/*
    # Install dependencies
    - apt -y --no-install-recommends install devscripts lintian
    - apt build-dep -y --no-install-recommends .
    # Generate change log
    - export DEBEMAIL=$CI_COMMIT_AUTHOR
    - dch -v "$(python3 -m setuptools_scm)" "automated build"
    # Run build in separate target
    - dpkg-buildpackage -A
    - lintian
    # Move files to archives
    - mkdir -p ./dist/$DIST
    - mv ../*.deb ./dist/$DIST/
  artifacts:
    paths:
      - ./dist/*
    expire_in: 1 day

package:minarca-server:deb:
  <<: *tox
  # Older image for pyinstaller
  image: python:3.12-bullseye
  stage: package
  needs: []
  variables:
    TOXENV: "pyinstaller"
  artifacts:
    paths:
    - "./dist/*_amd64.deb"
    expire_in: 1 day

.test-package: &test-package
  stage: test-package
  before_script:
    - *apt-minarca-source
  parallel:
    matrix:
      - DIST: [trixie, forky, questing, resolute]

test-package:rdiffweb:
  <<: *test-package
  needs:
    - package:rdiffweb:deb
  script:
    - apt install -y ./dist/$DIST/rdiffweb*.deb
    - rdiffweb --version
    - (/usr/bin/rdiffweb &)
    - timeout 60 bash -c 'until curl --silent http://localhost:8080; do sleep 1; done'

test-package:minarca-server:
  <<: *test-package
  needs:
    - package:minarca-server:deb
  script:
    - apt install -y ./dist/minarca-server_*_amd64.deb
    - /opt/minarca-server/minarca-server --version
    - (/opt/minarca-server/minarca-server --logfile= &)
    - timeout 60 bash -c 'until curl --silent http://localhost:8080; do sleep 1; done'

publish:sonar:
  stage: sonar
  allow_failure: true
  needs: [py3, minarca]
  image: sonarsource/sonar-scanner-cli
  only:
    variables:
      - $SONAR_URL
      - $SONAR_TOKEN
  variables:
    SONAR_PROJECT_BASE_DIR: "${CI_PROJECT_DIR}"
    SONAR_KEY: "$CI_PROJECT_NAME${CI_COMMIT_TAG:+-dev}"
    # Disable git shallow clone
    GIT_STRATEGY: clone
    GIT_DEPTH: 0
  script:
    - sonar-scanner -X
      -Dsonar.python.coverage.reportPaths=coverage-*.xml
      -Dsonar.python.xunit.reportPaths=xunit-*.xml
      -Dsonar.host.url=$SONAR_URL
      -Dsonar.token=$SONAR_TOKEN
      -Dsonar.projectKey=$SONAR_KEY
      -Dsonar.projectVersion=$(git describe)
      -Dsonar.qualitygate.wait=True

publish:docker:
  needs:
    - package:docker
  image: docker:20
  services:
    - name: docker:20-dind
  only:
    variables:
      - $DOCKER_USR
      - $DOCKER_PWD
  parallel:
    matrix:
      - PKGAPP: rdiffweb
      - PKGAPP: minarca-server
  script: |
    set -x
    docker login $DOCKER_REGISTRY -u $DOCKER_USR -p $DOCKER_PWD
    docker load --input dist/$PKGAPP*.tar
    # Push commit hash
    docker tag $PKGAPP ikus060/$PKGAPP:$CI_COMMIT_SHORT_SHA
    docker push ikus060/$PKGAPP:$CI_COMMIT_SHORT_SHA
    # Push branch name
    docker tag $PKGAPP ikus060/$PKGAPP:$CI_COMMIT_REF_SLUG
    docker push ikus060/$PKGAPP:$CI_COMMIT_REF_SLUG
    # Push tags
    if [ -n "$CI_COMMIT_TAG" ]; then
      docker tag $PKGAPP ikus060/$PKGAPP:$CI_COMMIT_TAG
      docker push ikus060/$PKGAPP:$CI_COMMIT_TAG
    fi
    # Push tag as latest
    case ${CI_COMMIT_TAG##*.} in
      [0-9]*)
        docker tag $PKGAPP ikus060/$PKGAPP:latest
        docker push ikus060/$PKGAPP:latest
        ;;
    esac
  stage: publish

publish:docker-readme:
  needs:
    - package:docker
  only:
    variables:
      - $DOCKER_USR
      - $DOCKER_PWD
      - $CI_COMMIT_TAG
  parallel:
    matrix:
      # Rdiffweb
      - PUSHRM_SHORT: A web interface to rdiff-backup repositories.
        PUSHRM_TARGET: docker.io/ikus060/rdiffweb
        PUSHRM_FILE: $CI_PROJECT_DIR/README.md
      # Minarca-Server
      - PUSHRM_SHORT: Your open-source, user-friendly data backup solution.
        PUSHRM_TARGET: docker.io/ikus060/minarca-server
        PUSHRM_FILE: $CI_PROJECT_DIR/minarca-server/docker/README.md
  image:
    name: chko/docker-pushrm
    entrypoint: ["/bin/sh", "-c"]
  variables:
    DOCKER_USER: $DOCKER_USR
    DOCKER_PASS: $DOCKER_PWD
    PUSHRM_DEBUG: 1
  script:
    # Keep top 400 lines to workarround Dockerhub limitation.
    - cp README.md README.md.orig
    - head -n 400 README.md.orig > README.md
    # Push file
    - /docker-pushrm
  stage: publish

publish:deb:
  needs:
    - package:rdiffweb:deb
    - package:minarca-server:deb
  only:
    variables:
      - $NEXUS_USR
      - $NEXUS_PWD
  parallel:
    matrix:
      - PKGAPP: rdiffweb
        DIST: [questing, resolute, trixie, forky]
      - PKGAPP: minarca-server
        DIST: [questing, resolute, trixie, forky]
  script: |
    set -e
    set -x
    if [[ "$CI_COMMIT_TAG" == *.+([0-9]) ]]; then
      APT_URL="$NEXUS_URL/repository/apt-release-${DIST}/"
    else
      APT_URL="$NEXUS_URL/repository/apt-dev-${DIST}/"
    fi
    # Look in DIST-specific folder first, fallback to dist root
    if ls ./dist/$DIST/$PKGAPP*.deb 2>/dev/null; then
      export FILE=$(ls -1 ./dist/$DIST/$PKGAPP*.deb)
    else
      export FILE=$(ls -1 ./dist/$PKGAPP*.deb)
    fi
    curl --fail -u "$NEXUS_USR:$NEXUS_PWD" -H "Content-Type: multipart/form-data" --data-binary "@$FILE" "$APT_URL"
  stage: publish

publish:wheel:
  stage: publish
  only:
    variables:
      - $NEXUS_USR
      - $NEXUS_PWD
      - $NEXUS_PYPI_URL
  needs:
    - package:py3
  script: |
    set -x
    # Publish wheel
    pip3 install wheel twine readme_renderer[md] --upgrade
    LANG="C.UTF-8" python3 -m readme_renderer README.md -o /tmp/README.html
    twine upload dist/*.whl dist/*.tar.gz -u $NEXUS_USR -p $NEXUS_PWD --repository-url $NEXUS_PYPI_URL
    if [ ! -z "$CI_COMMIT_TAG" ]; then
      twine upload dist/*.whl dist/*.tar.gz -u $PYPI_USR -p $PYPI_PWD
    fi

publish:doc:
  stage: publish
  only:
    variables:
      - $NEXUS_USR
      - $NEXUS_PWD
      - $NEXUS_URL
  needs:
    - doc
  script: |
    # publish to nexus
    pip install setuptools_scm
    export VERSION=$(python3 -m setuptools_scm)
    cd .tox/doc/tmp/html
    find * -type f | while read -r FILE
    do
      # Publish to nexus
      curl --fail -u "$NEXUS_USR:$NEXUS_PWD" --upload-file "$FILE" "$NEXUS_URL/repository/archive/rdiffweb/$VERSION/doc/$FILE"
      sleep 2
      # Because Nexus server fail, make sure the file is accessible.
      curl --fail "$NEXUS_URL/service/rest/repository/browse/archive/rdiffweb/$VERSION/doc/$(dirname $FILE)/" | grep "$(basename $FILE)"
    done

deploy:dev:
  only:
    variables:
      - $GITLAB_ANSIBLE_TOKEN
  allow_failure: True
  needs:
    - package:rdiffweb:deb
    - package:minarca-server:deb
  parallel:
    matrix:
      - PKGAPP: rdiffweb
        TRIGGER: RDIFFWEB_VERSION
        DIST: trixie
      - PKGAPP: minarca-server
        TRIGGER: MINARCA_VERSION
  image: heitormotta/pipeline-trigger:2.9.0
  script: |
    set -e
    set -x
    if ls ./dist/$DIST/$PKGAPP*.deb 2>/dev/null; then
      export FILE=$(ls -1 ./dist/$DIST/$PKGAPP*.deb)
    else
      export FILE=$(ls -1 ./dist/$PKGAPP*.deb)
    fi
    export DEB_VERSION=$(echo "$FILE" | cut -d '_' -f 2)
    echo DEB_VERSION=$DEB_VERSION
    # Trigger ansible-config pipeline
    trigger -a "$ANSIBLE_PIPELINE_GITLAB_API_TOKEN" -t master -e "$TRIGGER=$DEB_VERSION" -p 36bae86778d901fc6b2d6453a41844 18716492
  stage: deploy
  variables:
    GIT_STRATEGY: none

e2e-test:minarca:deb:
  allow_failure: True
  variables:
    GIT_STRATEGY: none
  needs:
  - deploy:dev
  image: buildpack-deps:$DIST
  parallel:
    matrix:
    - DIST: [bullseye, bookworm, trixie, jammy, noble, plucky]
  script:
    # Install latest minarca-client release
    - apt update
    - apt install -y apt-transport-https ca-certificates lsb-release gpg
    - curl -L https://www.ikus-soft.com/archive/minarca/public.key | gpg --dearmor > /usr/share/keyrings/minarca-keyring.gpg
    - echo "deb [arch=amd64 signed-by=/usr/share/keyrings/minarca-keyring.gpg] https://nexus.ikus-soft.com/repository/apt-dev-$(lsb_release -sc)/ $(lsb_release -sc)-dev main" > /etc/apt/sources.list.d/minarca.list
    - apt update
    - apt install -y minarca-client
    # Smoke test
    - minarca --version
    - /opt/minarca/minarcaw --version
    # Check backup
    - minarca -d link --remoteurl "$MINARCA_DEV_REMOTE_URL" --username "$MINARCA_DEV_USERNAME" --password "$MINARCA_DEV_PASSWORD" --name "e2e-test-${DIST}-${CI_JOB_ID}"
    - minarca -d status
    - minarca -d include /etc /var /home
    - minarca -d backup --force
  stage: e2e-test

e2e-test:minarca:linux:
  allow_failure: 
  variables:
    GIT_STRATEGY: none
  needs:
  - deploy:dev
  image: buildpack-deps:jammy
  script:
    # Install latest minarca-client release
    - apt update
    - apt install -y cron openssh-client locales locales-all
    - wget https://www.ikus-soft.com/archive/minarca/minarca-client-latest.tar.gz
    - tar -zxvf ./minarca-client-latest.tar.gz --strip 1
    # Smoke test
    - ./minarca --version
    - ./minarcaw --version
    # Check backup
    - ./minarca -d link --remoteurl "$MINARCA_DEV_REMOTE_URL" --username "$MINARCA_DEV_USERNAME" --password "$MINARCA_DEV_PASSWORD" --name "e2e-test-linux-${CI_JOB_ID}"
    - ./minarca -d include /etc /var /home
    - ./minarca -d status
    - ./minarca -d backup --force
  stage: e2e-test

e2e-test:minarca:macos:
  allow_failure: True
  variables:
    GIT_STRATEGY: none
  needs:
  - deploy:dev
  before_script:
  - rm -Rf /Applications/Minarca.app
  - rm -Rf $HOME/Library/Preferences/Minarca
  script:
  # Install latest minarca-client release
  - "[ ! -e /Volumes/Minarca ] || hdiutil detach /Volumes/Minarca"
  - curl -L -O https://www.ikus-soft.com/archive/minarca/minarca-client-latest.dmg
  - hdiutil attach ./minarca-client-latest.dmg
  - cp -r /Volumes/Minarca/Minarca.app /Applications/
  # Smoke test
  - /Applications/Minarca.app/Contents/MacOS/minarca --version
  - /Applications/Minarca.app/Contents/MacOS/minarcaw --version
  # Check backup
  - /Applications/Minarca.app/Contents/MacOS/minarca -d forget --force
  - /Applications/Minarca.app/Contents/MacOS/minarca -d link --remoteurl "$MINARCA_DEV_REMOTE_URL" --username "$MINARCA_DEV_USERNAME" --password "$MINARCA_DEV_PASSWORD" --name "e2e-test-macos-${CI_JOB_ID}"
  - /Applications/Minarca.app/Contents/MacOS/minarca -d include "$HOME/Documents"
  - /Applications/Minarca.app/Contents/MacOS/minarca -d status
  - /Applications/Minarca.app/Contents/MacOS/minarca -d backup --force
  stage: e2e-test
  tags:
  - macos
  variables:
    LC_ALL: "en_US.UTF-8"

e2e-test:minarca:win32:
  allow_failure: True
  variables:
    GIT_STRATEGY: none
  needs:
  - deploy:dev
  script:
  # Install minarca
  - Invoke-WebRequest -Uri https://www.ikus-soft.com/archive/minarca/minarca-client-latest.exe -OutFile minarca-client-latest.exe
  - Start-Process -wait "minarca-client-latest.exe" /S
  - dir "C:\Program Files\Minarca"
  - $Env:path = "C:\Program Files\Minarca;$Env:path"
  - $Env:path
  # Smoke test
  - minarca.exe --version
  - minarcaw.exe --version
  # Check backup
  - minarca.exe -d forget --force
  - minarca.exe -d link --force --remoteurl "$MINARCA_DEV_REMOTE_URL" --username "$MINARCA_DEV_USERNAME" --password "$MINARCA_DEV_PASSWORD" --name "e2e-test-win32-${CI_JOB_ID}"
  - minarca.exe -d include /etc /var /home
  - minarca.exe -d status
  - minarca.exe -d backup --force
  stage: e2e-test
  tags:
  - windows

e2e-test:docker:
  image: docker:20
  stage: e2e-test
  variables:
    GIT_STRATEGY: none
  parallel:
    matrix:
      - PKGAPP: rdiffweb
      - PKGAPP: minarca-server
  needs:
    - publish:docker
    - package:minarca-server:deb
  services:
    - docker:dind
  script:
    - docker run --privileged -d --name $PKGAPP -p 8080:8080 ikus060/$PKGAPP:$CI_COMMIT_SHORT_SHA
    - timeout 60 sh -c 'until docker inspect --format="{{.State.Running}}" $PKGAPP 2>/dev/null | grep -q "true" && wget --spider http://docker:8080 2>/dev/null; do sleep 1; done'
    - docker ps
