sonar.exclusions=**/test_*.py,rdiffweb/test.py,**/doc/conf.py,**/*.js
sonar.python.version=3.11, 3.12, 3.13

# Ignore few rules
sonar.issue.ignore.multicriteria=e1,e2,e3
# Prefer tag over ARIA role
sonar.issue.ignore.multicriteria.e1.ruleKey=Web:S6819
sonar.issue.ignore.multicriteria.e1.resourceKey=**/*
# Attributes deprecated in HTML5 should not be used
sonar.issue.ignore.multicriteria.e2.ruleKey=Web:S1827
sonar.issue.ignore.multicriteria.e2.resourceKey=rdiffweb/templates/email_*.html
# Tables should have headers
sonar.issue.ignore.multicriteria.e3.ruleKey=Web:S5256
sonar.issue.ignore.multicriteria.e3.resourceKey=rdiffweb/templates/email_*.html
