#!/bin/sh
set -ex

# dep8 smoke test for rdiff-backup
# Author: Patrik Dufresne <patrik@ikus-soft.com>
#
# This very simple test just checks that the binary starts

rdiffweb --help 2>&1 | grep 'usage:'
