# Copyright (C) 2021 IKUS Software inc. All rights reserved.
# IKUS Software inc. PROPRIETARY/CONFIDENTIAL.
# Use is subject to license terms.

MINARCA_USER=minarca
MINARCA_HOME=/backups/
MINARCA_ETC=/etc/minarca
MINARCA_LOG=/var/log/minarca
MINARCA_SESSION=/var/lib/minarca

KEYRING_PATH=/usr/share/keyrings/minarca-keyring.gpg

PUBLIC_KEY="-----BEGIN PGP PUBLIC KEY BLOCK-----

mQENBF6YcF8BCADKougGz5qNYavaQRW/IR4pRDLKreLx+UqhgGvoW9WnPixm5gLI
QC3QxZ/LuF2pQcbrVWlZ30JFsvqTIdfupOzGV1RRjct5DEXz5bfZbL15GSDHxkKE
3yFNlGOWPioboSHkIviL3YG2L7bHDoML1esYZiCyRas5DmhGGZHFd5N3ipP6hYrk
9z2EiWL0IoJRsqwSj+l5yMR9twsHog1OvQjjHJb9xcmvXE52y2/FK4BtoFXAHGXg
Uq2ml9g4gGx4QTc52rRbTbvjSHAj/oUxOlK2qQK6My6BB6qRZX0Lx8dXX53Afoa3
BsdTF6FOskmjXWyEP+XORuwwtLMza5eawZ8HABEBAAG0KVBhdHJpayBEdWZyZXNu
ZSA8aW5mb0BwYXRyaWtkdWZyZXNuZS5jb20+iQFOBBMBCAA4FiEEO4KZw0kmFpVz
Kq51iB9rLT5km2oFAl6YcJsCGwMFCwkIBwMFFQoJCAsFFgIDAQACHgECF4AACgkQ
iB9rLT5km2pUQwf/UEaYbxIN3jNgbUVgrbaluMUu7TWbuVfh0uPXp0YChiyyB13w
DoRPaOEqZz65VVwnPcv4yAVv44/d4Q69KDGWs+oYU8CXRP2bL6YXe/kDKIP0EPZ3
SAq+o0iBponoDyYRydycvUVDbgEkohIAUoKUq+Gn0MsJXS59XyGTLrfVWHZ79tJo
PWX91v3agH1ybTX9fsOdlF9ToaZiWO3w96M6BQtQDBkNPUzWEozhvCnAvDQASSih
tJuimhdtYiUah2mShOXmn+g+awkZe5Vp6QE5ithNQYOjURe5jBtsTIXAJPKAyEAL
HcseQXNBncBj8W2E+7ytGMxh/9R3N5biQcfP5LQjUGF0cmlrIER1ZnJlc25lIDxp
a3VzMDYwQGdtYWlsLmNvbT6JAU4EEwEIADgWIQQ7gpnDSSYWlXMqrnWIH2stPmSb
agUCXphwXwIbAwULCQgHAwUVCgkICwUWAgMBAAIeAQIXgAAKCRCIH2stPmSbajo8
B/9uFWplTJ8oap8wGQVHFTsRi6ZSbHN5CpMnkvmU5ftnAC6OtsWVNY6L74GDxO0M
QiWuUTLeNTJPM9Nu4RrkBO30CLVjSyqQBaUDWs1rBsNEntzL9cy95DFtSYiDYXI/
B1/ZlYcsDCH+Ep5mRrS63sZaRkgud2AsLzXuiF1m8zyJXyfxStJKegTmAR8y6Cc1
cTTONjAUsiTXqtg1uNGldn0Q5sZD5HWYqdYZP2JfNswQG/+3HK/eRghDxqQNvCq9
Vwfq7nvAOelXRbwRZCShsL0MRrgXDAwD4xrIlma3V6v8NRA1euH+zZSqLBA4AmOC
wv329jYqmvcRiONI6xsVT0tmtCZQYXRyaWsgRHVmcmVzbmUgPHBhdHJpa0Bpa3Vz
LXNvZnQuY29tPokBTgQTAQgAOBYhBDuCmcNJJhaVcyqudYgfay0+ZJtqBQJemHCr
AhsDBQsJCAcDBRUKCQgLBRYCAwEAAh4BAheAAAoJEIgfay0+ZJtqMIsH/20WSOgZ
uHmhNTXjwxN+Tej17Tsh3qITS+cMXK8SVG2W4vXai9SxV4r+OdDLvrExTqw1zJny
7GVRL/SmEfxv+vIsmh2ncy4IXfWW9gMER36YRIRKVNvvCA3xtWJgZb8asX1cBXRI
jW1vKrCemo2aALGXJzL5U9JCUhvSIoakPCBgeJWG4ds+0KLqWQhAwR5WhCyw7CPm
3T0ec6Op/jqN0sEsOd4W4uf8yx7ITlCvMWoO0qkVeSQT0tyuQ8FtZkV47Vu8LJxI
jb6nujQH5gOGurHv11r87U7KvDiuninbdyf0PGdzxxmy8kDYgIahbkTvfz+BKD1p
ECLTJNAE/uvrmIa5AQ0EXphwXwEIANm8KsOIpcQwaH+JZnEewtOtXL90YW87oE8o
VME1SPOutl2+BNHdW1Y5R0nzyXJ16itW+wPG4o5O6VTKQu4mA64MGB3gvaUUomrG
KBd1kIfNDxWhUoxx8+nc5IpAKod9ULpNfTAUQOoD7bU85ign8q3OJ20Dc80iy5Im
XK4f6g+ySQLU2USU28Su9D63p+yhomf1rz9/z1bBDxf+vGtuZshNk9txTW8EsI3f
PihOjTJ2WnwD7XCnHXi5Y1XUpAMol52jMmYaQkUmhUixumHEMHcpfy9GzK3x4bkk
qLRaNo9x6inR1Aq2YTfCZ2QZooFoHaWGe3EF6+L8QyPAmQz2X5MAEQEAAYkBNgQY
AQgAIBYhBDuCmcNJJhaVcyqudYgfay0+ZJtqBQJemHBfAhsMAAoJEIgfay0+ZJtq
k0wIAIya7H20ucjRdLQoJ/YL/kdElEhmQq3ilsusetXKFFQtehlsRrGd8YTdCU9u
beuWMS77oXv+IT04t9yLA2p4qS5oXGebs4/WdRfrwjtpiXBk2jMSgiXkxx/qGB0Z
UaOzac0f+vJyA+0b+GlVCUgmxwyUmmWyxXEr8l7XZKSNyOdz2AkmTudY7zb3jERN
rmLsCq3WHCQgWyruOe13NKE2k4rYfj463d7Rd+hbQtZlBOl2LBYusnU6mtF0uma6
gQE3m8lXH8dR1xPpHljQOAViq/QvCyBjviRwNZ38JxooZZxIPhvTqaMI8567l3cH
6AGo+q1G2pxg1iRc4nLxadLB0p0=
=EPRn
-----END PGP PUBLIC KEY BLOCK-----"

PREAMBLE="## THIS FILE IS AUTOMATICALLY UPDATED ##
# Any update to this files may get lost."

add_apt_repo() {
  APT_CONFIG="`which apt-config 2> /dev/null`"
  eval $("$APT_CONFIG" shell APT_SOURCESDIR 'Dir::Etc::sourceparts/d')


  NEW_VERSION=$(zcat /usr/share/doc/minarca-server/changelog.gz | dpkg-parsechangelog -l- -SVersion)
  case $NEW_VERSION in
  *dev*)
    CHANNEL=dev;;
  *rc*)
    CHANNEL=dev;;
  *)
    CHANNEL=release;;
  esac

  echo "$PUBLIC_KEY" | gpg --dearmor > "$KEYRING_PATH"
  echo "$PREAMBLE" > "$APT_SOURCESDIR/minarca.list"
  echo "deb [arch=amd64 signed-by=$KEYRING_PATH] https://nexus.ikus-soft.com/repository/apt-$CHANNEL-$(lsb_release -sc)/ $(lsb_release -sc) main" >> "$APT_SOURCESDIR/minarca.list"
}

case "$1" in
  configure)
        if ! getent passwd "$MINARCA_USER" >/dev/null; then
            adduser --quiet --system --home "$MINARCA_HOME" --shell /bin/bash \
                --no-create-home --gecos 'minarca repository hosting' \
                --group "$MINARCA_USER"
        fi
        # Create folder for logs & session
        mkdir -p "$MINARCA_ETC" "$MINARCA_LOG" "$MINARCA_HOME" "$MINARCA_SESSION"
        chown -R minarca:minarca "$MINARCA_ETC" "$MINARCA_SESSION"
        chown -R minarca:adm "$MINARCA_LOG"
        chmod -R 0750 "$MINARCA_ETC" "$MINARCA_LOG" "$MINARCA_SESSION"
        chown minarca:minarca "$MINARCA_HOME"
        chmod 0750 "$MINARCA_HOME"
        # Enable user namespace (Disable debian hardening)
        if [ -f /proc/sys/kernel/unprivileged_userns_clone ]; then
          echo 1 > /proc/sys/kernel/unprivileged_userns_clone
          echo 'kernel.unprivileged_userns_clone=1' > /etc/sysctl.d/00-minarca-local-userns.conf
        fi
        # Add APT repository if not configured
        if [ -e "$APT_SOURCESDIR/minarca.list" ]; then
          add_apt_repo
        fi
    ;;
esac

#DEBHELPER#

exit 0
