#!/bin/sh

set -e

case "${1}" in
	purge)
		# Remove default session directory
		rm -rf /var/lib/rdiffweb
		# Remove symlink
		rm -f /usr/lib/python3/dist-packages/rdiffweb/static/js/chart.min.js
		rm -f /usr/lib/python3/dist-packages/rdiffweb/static/js/chartkick.min.js
		;;

	remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)

		;;

	*)
		echo "postrm called with unknown argument \`${1}'" >&2
		exit 1
		;;
esac

#DEBHELPER#

exit 0
