#!/bin/sh

set -e

case "${1}" in
	configure)
		# Encforce permissions on /etc/rdiffweb
		mkdir -p --mode 750 /etc/rdiffweb

		# Create default session directory
		mkdir -p /var/lib/rdiffweb/session
		
		# Create default log directory
		mkdir -p /var/log/rdiffweb

		;;

	abort-upgrade|abort-remove|abort-deconfigure)

		;;

	*)
		echo "postinst called with unknown argument \`${1}'" >&2
		exit 1
		;;
esac

#DEBHELPER#

exit 0
