#!/bin/sh
# rdiffweb, A web interface to rdiff-backup repositories
# Copyright (C) 2014 rdiffweb contributors
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Basic support for the Linux Standard Base Specification 3.1.0
### BEGIN INIT INFO
# Provides: rdiffweb
# Required-Start: $network $local_fs
# Required-Stop: $network
# Default-Start: 2 3 5
# Default-Stop: 0 6
# Description: Manages the rdiffweb daemon
### END INIT INFO

RDIFFWEB="/usr/local/bin/rdiffweb"
PIDFILE="/var/run/rdiffweb"
LOGFILE="/var/log/rdiffweb.log"

SUCCESS_MSG="[71G done"
ERROR_MSG="[71Gfailed"

if [ -f /etc/init.d/functions ]; then
 . /etc/init.d/functions
fi

# This script won't be able to run without root privileges.
if [ `id -u` -ne 0 ]; then
    echo "Error: this script must be run as root."
    exit 1
fi

# See how we were called.
case "$1" in
    start)
        echo -n "Starting rdiffweb..."
        "$RDIFFWEB" --pid-file="$PIDFILE" \
        --log-file="$LOGFILE" \
        --background
        RETVAL="$?"
        if [ "$RETVAL" = "0" ]; then
        	echo $SUCCESS_MSG
       	else
       		echo $ERROR_MSG
       	fi
        exit 0
    ;;

    stop)
        if [ -e "$PIDFILE" ]; then
            echo -n "Stopping rdiffweb..."
            kill `cat "$PIDFILE" 2>/dev/null` > /dev/null 2>&1
            rm $PIDFILE > /dev/null 2>&1
            echo $SUCCESS_MSG
            exit 0
        else
            echo -n "rdiffweb is not running"
            echo $ERROR_MSG
            exit 1
        fi
    ;;

    status)
        echo -n "rdiffweb "
        if [ -e "$PIDFILE" ]; then
            echo "is running."
            exit 0
        else
            echo "is not running."
            exit 1
        fi
    ;;

    restart)
        "$0" stop && "$0" start
    ;;

    *)
        echo "Usage: `basename "$0"` {start|stop|status|restart}"
        exit 1
esac

exit 0